# Симплекс метод

In [1]:
import numpy as np
from symplexmethod import symplex, main, initial

ROUND_DEC_POINTS = 6 # for rounding

In [2]:
# the first example
c0 = np.array([1, 1, 0, 0, 0])
A0 = np.array([[-1, 1, 1, 0, 0],
              [1, 0, 0, 1, 0],
              [0, 1, 0, 0, 1]])
b0 = np.array([1, 3, 2])
x0 = np.array([0, 0, 1, 3, 2])
B0 = np.array([2, 3, 4])

# TODO: more tests

tests1 = [
    {
        'c': c0,
        'A': A0,
        'x': x0,
        'b': b0,
        'B': B0,
    },
]

### Тестирование основной фазы симплекс метода

In [3]:
for i, test in enumerate(tests1):
    print(f'Test #{i+1}:')
    try:
        solution = symplex.scipy_solve(test['c'], test['A'], test['b'])
        x = [round(x, ROUND_DEC_POINTS) for x in solution.x]
        print(f'\tScipy solution: {x}')
    except:
        print('\tScipy function failed')
    try:
        solution = main.run(test['c'], test['A'], test['x'], test['B'])
        if solution['solved']:
            print(f'\tCustom algorithm solution: {solution.get("x")}')
        else:
            print(f'\tCustom algorithm failed; details:\n\t{solution.get("details")}')
    except Exception as e:
        print(f'\tCustom algorithm had an inner error\n\t{e}')

Test #1:
	Scipy solution: [3.0, 2.0, 2.0, 0.0, 0.0]
	Custom algorithm solution: [3 2 2 0 0]


### Тестирование начальной фазы симплекс метода

In [4]:
tests2 = [
    {
        'c': [1, 0, 0],
        'A': [[1, 1, 1], [2, 2, 2]],
        'b': [0, 0]
    },
    {
        'c': c0,
        'A': A0,
        'b': b0
    },
    {
        'c': [-1, 1, 0],
        'A': [[2, 1, 3], [1, -3, 1], [1, 11, 3]],
        'b': [1, -3, 11]
    }
]

In [5]:
for i, test in enumerate(tests2):
    print(f'Test #{i+1}:')
    try:
        solution = initial.run(test['c'], test['A'], test['b'])
        if solution['success']:
            print(f'\tCustom algorithm solution:\n\tx = {solution.get("x")},\n\tB = {solution.get("B")},\n\tA:\n{solution.get("A")},\n\tb = {solution.get("b")}')
        else:
            print(f'\tCustom algorithm failed; details:\n\t{solution.get("details")}')
    except Exception as e:
        print(f'\tCustom algorithm had an inner error:\n\t{e}')

Test #1:
	Custom algorithm solution:
	x = [0. 0. 0.],
	B = [0],
	A:
[[1 1 1]],
	b = [0]
Test #2:
	Custom algorithm solution:
	x = [3. 2. 2. 0. 0.],
	B = [1, 2, 0],
	A:
[[-1  1  1  0  0]
 [ 1  0  0  1  0]
 [ 0  1  0  0  1]],
	b = [1 3 2]
Test #3:


KeyboardInterrupt: 

### Тестирование (полного алгоритма) симплекс метода